
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GitHubSample.Model
{

using System;
    using System.Collections.Generic;
    
public partial class GitHubRepo
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Language { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }

    public string OwnerName { get; set; }

    public string OwnerAvatarUrl { get; set; }

    public int GitHubRepoId { get; set; }

}

}
